name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort ruff mypy pytest pytest-asyncio httpx structlog types-requests
      - name: Lint (ruff)
        run: ruff check --output-format=github .
      - name: Format check (black)
        run: black --check --line-length 100 .
      - name: Imports (isort)
        run: isort --profile black --check-only .
      - name: Type check (mypy)
        run: mypy --strict --warn-redundant-casts --warn-unused-ignores --no-implicit-optional .
      - name: Run tests
        env:
          MONGODB_URI: mongodb://localhost:27017/test
        run: pytest -q
